### ISSUE TITLE
Tag a new version and create first release

### ISSUE THREAD

**Issue by felker** [IAS-Astrophysics/athenak#597]
The tag `v1.0` is nearly a year old, and there are no GitHub releases tied to any tag. 

Given the recent bump in Kokkos from 4.1 to 4.4.x, suggested to tag `v1.1` sometime soon and mint a matching GitHub release to highlight it.

**Comment by jmstone** [comment]
Thanks for the suggestion, Kyle.  I'm trying to keep AthenaK pretty low-maintenance, so there won't be many versions and/or official releases.  We need to clean up the code a lot now that the method papers have been submitted, and update the wiki.  Once all that is done I will probably create a new tag.
